"""Expose schema-generated annotation models, SAB identifiers, and record states."""

from enum import StrEnum
from uuid import UUID, uuid4

from go_standard_annotation_schema.datamodel.go_standard_annotation_schema import (
    Annotation,
    AnnotationExtension,
    AnnotationProperties,
)

__all__ = [
    "Annotation",
    "AnnotationExtension",
    "AnnotationOrigin",
    "AnnotationProperties",
    "AnnotationStatus",
    "ChangeSource",
    "new_annotation_id",
]


class AnnotationStatus(StrEnum):
    """Whether an annotation is current or soft-deleted."""

    ACTIVE = "active"
    DELETED = "deleted"


class AnnotationOrigin(StrEnum):
    """How an annotation entered SAB: created in SAB or imported from GPAD."""

    DIRECT = "direct"
    IMPORT = "import"


class ChangeSource(StrEnum):
    """The workflow recorded on an annotation version.

    Version history uses this to show how each change was made, and annotation
    refreshes use it to tell local edits apart from changes SAB made itself.
    """

    API = "api"
    """A direct create, update, or delete request."""
    CHANGE_SET = "change_set"
    """An accepted change-set proposal."""
    ONTOLOGY_REFRESH = "ontology_refresh"
    """An automatic replacement of an obsolete ontology term."""
    ANNOTATION_REFRESH = "annotation_refresh"
    """An import of a group's annotations from a GPAD source."""
    ANNOTATION_CUTOVER = "annotation_cutover"
    """The final GPAD import made when a group moves to SAB management."""


def new_annotation_id() -> UUID:
    """Generate a unique SAB identifier for an annotation.

    Returns:
        A new UUID generated by SAB.
    """
    return uuid4()
