"""Expose schema-generated annotation models and create SAB identifiers."""

from uuid import UUID, uuid4

from go_standard_annotation_schema.datamodel.go_standard_annotation_schema import (
    Annotation,
    AnnotationExtension,
    AnnotationProperties,
)

__all__ = [
    "Annotation",
    "AnnotationExtension",
    "AnnotationProperties",
    "new_annotation_id",
]


def new_annotation_id() -> UUID:
    """Generate a unique SAB identifier for an annotation.

    Returns:
        A new UUID generated by SAB.
    """
    return uuid4()
