"""Expose schema-generated annotation models, SAB identifiers, and record states."""

from enum import StrEnum
from uuid import UUID, uuid4

from go_standard_annotation_schema.datamodel.go_standard_annotation_schema import (
    Annotation,
    AnnotationExtension,
    AnnotationProperties,
)

__all__ = [
    "Annotation",
    "AnnotationExtension",
    "AnnotationOrigin",
    "AnnotationProperties",
    "AnnotationStatus",
    "new_annotation_id",
]


class AnnotationStatus(StrEnum):
    """Whether an annotation is current or soft-deleted."""

    ACTIVE = "active"
    DELETED = "deleted"


class AnnotationOrigin(StrEnum):
    """How an annotation entered SAB: created in SAB or imported from GPAD."""

    DIRECT = "direct"
    IMPORT = "import"


def new_annotation_id() -> UUID:
    """Generate a unique SAB identifier for an annotation.

    Returns:
        A new UUID generated by SAB.
    """
    return uuid4()
